Crash on "Got NULL buffer!" error
FD-/RPiPlay pull request #159
Opened 2020-09-24 08:05 UTC by bedrin

I'm mirroring my old iPad Air 2 screen to RPiPlay on 3B+ and sometimes getting "Got NULL buffer!" error after a few days.
It doesn't recover after this error (I cannot reconnect my iPad to it) so I have to restart RPiPlay

In my case restarts are automated (I'm running RPiPlay inside Docker) so it is easier for me to crash RPiPlay in case of this error.

Not sure if you want to merge it but I just want to leave it here in case some one else faces the same issue

2020-09-24 19:21 UTC, pallas requested changes
Sorry, where did it actually crash? There are plenty of reasons that you might not be able to grab a buffer and blindly crashing does not seem like an appropriate outcome. This might also wallpaper over a resource leak that should be fixed at the source.

2020-09-24 19:30 UTC, pallas commented
Ohhh, you're saying it gets a NULL buffer and then it hangs forever?

2020-09-24 21:07 UTC, FD- commented
Does modifying the RAM split in favor of the GPU maybe fix the problem?

2021-11-06 12:34 UTC, FD- commented
Sorry it took me so long to get to this issue! The PR seems like a good idea!

2021-11-06 12:34 UTC, merged